version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=discount_codes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data